### ISSUE TITLE
Need URL rewrite to add trailing slash

### ISSUE THREAD

**Issue by pascalandy** [pascalandy/docker-stack-this#10]
Need to try this solution

https://github.com/containous/traefik/issues/563#issuecomment-382960068

**Comment by hartzell** [comment]
Go for it!  It comes with a **full money-back** guarantee (too bad markdown doesn't support the `<blink>` tag...)!

But seriously, this is tricksier than I've ever gotten with Traefik, I'd love feedback.  You can do an analogous, static trick in the `traefik.toml`.

**Comment by pascalandy** [comment]
Thanks for jumping in :) 
Do you have a `traefik.toml` example as well ?

**Comment by hartzell** [comment]
Dropped it over in containous/traefik#563.

**Comment by hartzell** [comment]
I just reread this and realized that I miss-understood you (I think).  I copied the `traefik.toml` that I've been using to containous/traefik#563.  If you meant, do I have a `traefik.toml` that does an analogous trick, statically, then no (not finished).  I screwed around with it but never finished the thought.

**Comment by pascalandy** [comment]
Ok thanks! I didn't tried it yet.

**Comment by pascalandy** [comment]
Fixed here: https://github.com/pascalandy/docker-stack-this/blob/1.53/traefik_stack5/toolportainer.yml#L38
