### ISSUE TITLE
Enable ACME (Letsencrypt)

### ISSUE THREAD

**Issue by pascalandy** [pascalandy/docker-stack-this#5]
Hey Folks!

I just finished a Docker Stack 3.1 compose file `docker swarm mode`. It work perfectly with play-with-docker and on my nodes. It rocks!
 
It runs:
```
1 instance of Traefik
3 instance of caddy
3 instance of caddy
3 instance of who by Emile
```

Now I’m trying to make it works with ACME and I’m stucked. Is there any gents who would enjoy adapting my Docker Stack with ACME and make the TLS magic happen?

Many cheers!
Pascal

https://github.com/pascalandy/docker-stack-this/tree/master/traefik-manager

P.S. This git project also have a setup where Traefik runs on workers nodes.

---

Was ask on [Slack](https://traefik.slack.com/archives/C0CDT22PJ/p1497071392758916)

**Comment by abusaidm** [comment]
Hello @pascalandy 
Are you still having issue getting LE to work with traefik?

Thanks

**Comment by pascalandy** [comment]
Hi,
I don't test LE anymore as I use CloudFlare for this. Do you have a PR to suggest?
